- name: Install and configure Nginx
  hosts: rhel2
  become: true # Run tasks with sudo privileges

  tasks:
    - name: Create nginx user and group
      ansible.builtin.user:
        name: nginx
        group: nginx
        home: /var/www/html
        shell: /sbin/nologin
        system: true

    - name: Set ownership of Nginx directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: nginx
        group: nginx
        recurse: true
      with_items:
        - /etc/nginx
        - /var/log/nginx

    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx # Adjust this based on your package manager (e.g., yum for CentOS)
        state: present

    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
